version: '3.8'

services:
  app:
    image: audiotexthub:latest
    ports:
      - "8080:3000"  # 将容器的3000端口映射到主机的8080端口
      - "3000:3000"  # 同时保留3000端口访问
    # 内存限制和健康检查
    deploy:
      resources:
        limits:
          memory: 1024M  # 限制最大内存为1GB
        reservations:
          memory: 512M   # 保留最少512MB内存
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WEB_URL=https://www.audiotexthub.pro
      - NEXT_PUBLIC_API_URL=http://154.201.76.130:3099
      - AUTH_URL=https://www.audiotexthub.pro
      # 其他环境变量...
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT_URL_S3=${AWS_ENDPOINT_URL_S3}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_BUCKET_ENDPOINT=${S3_BUCKET_ENDPOINT}
      - BAIDU_TRANSLATE_APPID=${BAIDU_TRANSLATE_APPID}
      - BAIDU_TRANSLATE_KEY=${BAIDU_TRANSLATE_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - NEXT_PUBLIC_GEMINI_API_KEY=${NEXT_PUBLIC_GEMINI_API_KEY}
      - NEXT_PUBLIC_ENABLE_PROTECT=${NEXT_PUBLIC_ENABLE_PROTECT}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
      - UMAMI_URL=${UMAMI_URL}
      - UMAMI_TOKEN=${UMAMI_TOKEN}
      - NEXT_PUBLIC_UMAMI_URL=${NEXT_PUBLIC_UMAMI_URL}
      - NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
      - NEXT_PUBLIC_UMAMI_SRC=${NEXT_PUBLIC_UMAMI_SRC}
      - INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY}
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_ENABLE_STRIPE=${NEXT_PUBLIC_ENABLE_STRIPE}
      - NEXT_PUBLIC_ENABLE_BILLING=${NEXT_PUBLIC_ENABLE_BILLING}
      - NEXT_PUBLIC_ENABLE_LANDINGPAGE=${NEXT_PUBLIC_ENABLE_LANDINGPAGE}
      - RESEND_EMAIL_FROM=${RESEND_EMAIL_FROM}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
    restart: unless-stopped